### ISSUE TITLE
NoSuchMethodError: me.modmuss50.rebornstorage.items.ItemBase.setMaxStackSize(I)Lnet/minecraft/item/Item

### ISSUE THREAD

**Issue by viveleroi** [TechReborn/RebornStorage#112]
i'm adding RebornStorage to an existing custom modpack, and am getting this error on boot.

RebornStorage-1.12.2-3.2.1.63-dev
RebornCore-1.12.2-3.9.3.324-universal
refinedstorage-1.6.3
forge-1.12.2-14.23.4.2705-universal (Current 1.12 recommended)

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RebornStorage (rebornstorage)
Caused by: java.lang.NoSuchMethodError: me.modmuss50.rebornstorage.items.ItemBase.setMaxStackSize(I)Lnet/minecraft/item/Item;
	at me.modmuss50.rebornstorage.items.ItemBase.<init>(ItemBase.java:11)
	at me.modmuss50.rebornstorage.items.ItemRebornStorageCellBase.<init>(ItemRebornStorageCellBase.java:17)
	at me.modmuss50.rebornstorage.items.ItemRebornStorageCell.<init>(ItemRebornStorageCell.java:18)
	at me.modmuss50.rebornstorage.init.ModItems.init(ModItems.java:18)
	at me.modmuss50.rebornstorage.RebornStorage.preinit(RebornStorage.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by modmuss50** [comment]
You are using the -dev jar, this is designed for developers. Download the jar named "RebornStorage-1.12.2-3.2.1.63.jar" from https://minecraft.curseforge.com/projects/rebornstorage/files/2595028

**Comment by viveleroi** [comment]
my mistake, thanks. Not sure how I got that, I just follow the download links on curseforge.
