### ISSUE TITLE
Game crash when crafting on v3.3.1.76

### ISSUE THREAD

**Issue by Dannerick** [TechReborn/RebornStorage#138]
This is with the latest release of RebornStorage v3.3.1.76. I built a new multiblock crafter, put in one pattern and an attempt to craft crashed my game with this error.

```
Time: 12/7/18 10:02 AM
Description: Ticking block entity

java.lang.AbstractMethodError: Method me/modmuss50/rebornstorage/tiles/CraftingNode.getSpeedUpgradeCount()I is abstract
	at me.modmuss50.rebornstorage.tiles.CraftingNode.getSpeedUpgradeCount(CraftingNode.java)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.updateCrafting(CraftingTask.java:607)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:849)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:172)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:211)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

When I restart my game with v3.2.2.65 of RebornStorage, it all works just fine.

**Comment by modmuss50** [comment]
Update refined storage
