### ISSUE TITLE
Error: CraftingNode.getSpeedUpgradeCount()I is abstract

### ISSUE THREAD

**Issue by Zeptotesla** [TechReborn/RebornStorage#143]
Hello,

I'm getting the following error on version 1.12.2-3.3.2.79 of the RebornStorage mod.

`java.lang.AbstractMethodError: Method me/modmuss50/rebornstorage/tiles/CraftingNode.getSpeedUpgradeCount()I is abstract
	at me.modmuss50.rebornstorage.tiles.CraftingNode.getSpeedUpgradeCount(CraftingNode.java)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.updateCrafting(CraftingTask.java:605)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:837)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:172)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:203)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
`
[crash-2019-03-14_23.07.54-server.txt](https://github.com/TechReborn/RebornStorage/files/2969237/crash-2019-03-14_23.07.54-server.txt)

This happened when I built a crafting multiblock, put a pattern inside and tried to craft that pattern.

**Comment by gigabit101** [comment]
Closing due to inactivity
