### ISSUE TITLE
Crash when Crafter Multiblock is Destroyed while Powered

### ISSUE THREAD

**Issue by misterperson** [TechReborn/RebornStorage#159]
repro steps:
Place down a creative controller
Make a valid multiblock crafter connected to the controller
break any block of the multiblock structure

Observation:
The multiblock gets destroyed during the tick, so the post tick update function still has a dangling reference to it.

```
[20:36:49] [Client thread/FATAL] [VanillaFix]: Minecraft ran into a problem! Report saved to: C:\Games\MultiMC\instances\1.12.2\.minecraft\crash-reports\crash-2020-11-10_20.36.31-server.txt
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2020-11-10 20:36:49 PST
Description: Exception in server tick loop

java.lang.NullPointerException
    at me.modmuss50.rebornstorage.tiles.CraftingNode.getPatternInventory(CraftingNode.java:349)
    at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.rebuild(CraftingManager.java:373)
    at me.modmuss50.rebornstorage.RebornStorageEventHandler.tick(RebornStorageEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_999_RebornStorageEventHandler_tick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by misterperson** [comment]
Oops was using an old version
