### ISSUE TITLE
MultiBlockCrafter Causing Server to Freeze

### ISSUE THREAD

**Issue by Sir-Will** [TechReborn/RebornStorage#38]
The server does freeze when loading an MultiBlockCrafter until it is removed.

Version: 1.10.2-1.0.3.30
Thread Lock:
```
com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.<init>(AbstractMapBasedMultimap.java:459)
com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection.iterator(AbstractMapBasedMultimap.java:450)
com.raoulvdberge.refinedstorage.apiimpl.util.ItemStackList.add(ItemStackList.java:24)
com.raoulvdberge.refinedstorage.apiimpl.storage.item.ItemStorageCache.add(ItemStorageCache.java:62)
com.raoulvdberge.refinedstorage.apiimpl.storage.item.ItemStorageCache.invalidate(ItemStorageCache.java:53)
com.raoulvdberge.refinedstorage.tile.TileController.rebuildPatterns(TileController.java:497)
RebornStorage.multiblocks.MultiBlockCrafter.onConnectionChange(MultiBlockCrafter.java:225)
RebornStorage.tiles.TileMultiCrafter.onConnected(TileMultiCrafter.java:168)
com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.rebuild(NetworkNodeGraph.java:140)
com.raoulvdberge.refinedstorage.api.network.INetworkNodeGraph.rebuild(INetworkNodeGraph.java:24)
com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:329)
org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231)
net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2803)
net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjp000(WorldServer.java:2790)
net.minecraft.world.World.func_72939_s(World.java:6012)
net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2157)
net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
java.lang.Thread.run(Thread.java:745)
```

**Comment by modmuss50** [comment]
sponge.....

**Comment by Sir-Will** [comment]
What about that? I'm 100% sure it happens without sponge too.

**Comment by modmuss50** [comment]
Can you try and get a full log without sponge then please?

**Comment by Sir-Will** [comment]
```
   java.lang.Thread.State: RUNNABLE
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.lambda$new$0(CraftingPattern.java:52)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern$$Lambda$723/1915019019.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.<init>(CraftingPattern.java:52)
	at com.raoulvdberge.refinedstorage.item.ItemPattern.create(ItemPattern.java:210)
	at RebornStorage.multiblocks.MultiBlockCrafter.rebuildPatterns(MultiBlockCrafter.java:206)
	at RebornStorage.multiblocks.MultiBlockCrafter.onConnectionChange(MultiBlockCrafter.java:225)
	at RebornStorage.tiles.TileMultiCrafter.onConnected(TileMultiCrafter.java:168)
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.rebuild(NetworkNodeGraph.java:140)
	at com.raoulvdberge.refinedstorage.api.network.INetworkNodeGraph.rebuild(INetworkNodeGraph.java:24)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:329)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by modmuss50** [comment]
Just checking that this is on 1.10?

**Comment by Sir-Will** [comment]
As stated above, yes.

**Comment by modmuss50** [comment]
I spoke to the Refined Storage dev and confirmed it's an issue in Refined Storage
