### ISSUE TITLE
Can't auto craft storage disks

### ISSUE THREAD

**Issue by cybercronx** [TechReborn/RebornStorage#46]
I just also realized that I cannot auto craft any of the new disks you added. It says I have all the stuff for it and it lets me click start but it never appears in the crafting monitor nor does it make it.

Here is the error that it puts out in the console.

[17:12:49] [Server thread/FATAL]: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException

at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]

at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]

at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]

at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chb.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]

at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

Caused by: java.lang.NullPointerException

at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.<init>(CraftingTask.java:70) ~[CraftingTask.class:?]

at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.onCraftingRequested(ItemGridHandler.java:200) ~[ItemGridHandler.class:?]

at com.raoulvdberge.refinedstorage.network.MessageGridCraftingStart.handle(MessageGridCraftingStart.java:44) ~[MessageGridCraftingStart.class:?]

at com.raoulvdberge.refinedstorage.network.MessageGridCraftingStart.handle(MessageGridCraftingStart.java:12) ~[MessageGridCraftingStart.class:?]

at com.raoulvdberge.refinedstorage.network.MessageHandlerPlayerToServer.lambda$onMessage$0(MessageHandlerPlayerToServer.java:13) ~[MessageHandlerPlayerToServer.class:?]

at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]

at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]

at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]

... 5 more

**Comment by LuQ3** [comment]
I have the same issue but with other items (refined storage cables).

[Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.<init>(CraftingTask.java:70) ~[CraftingTask.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.onCraftingRequested(ItemGridHandler.java:200) ~[ItemGridHandler.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageGridCraftingStart.handle(MessageGridCraftingStart.java:44) ~[MessageGridCraftingStart.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageGridCraftingStart.handle(MessageGridCraftingStart.java:12) ~[MessageGridCraftingStart.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageHandlerPlayerToServer.lambda$onMessage$0(MessageHandlerPlayerToServer.java:13) ~[MessageHandlerPlayerToServer.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
