### ISSUE TITLE
Multiblock crafter don't craft some items.

### ISSUE THREAD

**Issue by LuQ3** [TechReborn/RebornStorage#53]
**When I trying request auto-crafting cables from Refined Storage mod it's nothing happend and crafting monitor was empty. I have all items needed to craft this. When I was looking into server log then I saw this:** 

[Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.<init>(CraftingTask.java:70) ~[CraftingTask.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.grid.handler.ItemGridHandler.onCraftingRequested(ItemGridHandler.java:200) ~[ItemGridHandler.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageGridCraftingStart.handle(MessageGridCraftingStart.java:44) ~[MessageGridCraftingStart.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageGridCraftingStart.handle(MessageGridCraftingStart.java:12) ~[MessageGridCraftingStart.class:?]
        at com.raoulvdberge.refinedstorage.network.MessageHandlerPlayerToServer.lambda$onMessage$0(MessageHandlerPlayerToServer.java:13) ~[MessageHandlerPlayerToServer.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by Kilmatar** [comment]
Same here! System stop processing Refined Storage cables as before.

**Comment by PongoSapiens** [comment]
This seems to affect items from several mods, the patterns work in a regular crafter but fail as above in the multi block crafter.

**Comment by EtherealUK** [comment]
Doesn’t just affect items from mods, my multiblock crafter won’t make sticks from planks...

**Comment by Legion7766** [comment]
I am experiencing this issue as well so far i have had issues with Mekanism pipes of any kind and refined storage cables not crafting and throwing this console error.
