### ISSUE TITLE
Version 3.0.2 crashes when loading a server

### ISSUE THREAD

**Issue by romulous75** [TechReborn/RebornStorage#70]
(Single player loads with v3.0.2, but a server does not.)

Just found the server bug where you cannot access the GUI of the multi block (v3.0.1). Tried the following to fix it:

Swapped out RebornStorage-1.12.2-3.0.1.26.jar with RebornStorage-1.12.2-3.0.2.32.jar
Pack: Direwolf20 1.12.2 (v1.3.0) which uses Refined Storage version 1.5.25

Got this when loading the server:

```
java.lang.ClassCastException: me.modmuss50.rebornstorage.tiles.CraftingNode cannot be cast to com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode
        at com.raoulvdberge.refinedstorage.tile.TileNode.getNode(TileNode.java:95)
        at com.raoulvdberge.refinedstorage.tile.TileNode.getNode(TileNode.java:22)
        at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph$Operator.apply(NetworkNodeGraph.java:143)
        at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode.visit(NetworkNode.java:192)
        at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph$Visitor.visit(NetworkNodeGraph.java:180)
        at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeGraph.rebuild(NetworkNodeGraph.java:59)
        at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:243)
        at net.minecraft.world.World.func_72939_s(World.java:1829)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by romulous75** [comment]
Looks like the new version updated the world in a way that the older version could not handle. Restored a backup and now running with the older Reborn Storage (which is broken).

**Comment by modmuss50** [comment]
I have no idea what could be causing this. @raoulvdberge ?

**Comment by Terminator81** [comment]
I have the same problem
i cannot access the gui if i play on a server....singleplayer works

**Comment by romulous75** [comment]
My issue is not that I cannot access the GUI. That is a known bug in 3.0.1 which the DW20 pack ships with. The issue is updating to the newest version on an existing world that used 3.0.1 to 3.0.2. It appears that something that 3.0.1 has added to the world is not compatible with 3.0.2

**Comment by jmarler** [comment]
Running RebornStorage 3.0.2.32 and RebornCore 3.5.2.171 I get this error upon connecting to my server:

```
java.lang.ClassCastException: me.modmuss50.rebornstorage.tiles.CraftingNode cannot be cast to com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNode
        at com.raoulvdberge.refinedstorage.tile.TileNode.getNode(TileNode.java:95) ~[TileNode.class:?]
        at com.raoulvdberge.refinedstorage.tile.TileNode.writeUpdate(TileNode.java:64) ~[TileNode.class:?]
        at com.raoulvdberge.refinedstorage.tile.TileBase.func_189517_E_(TileBase.java:72) ~[TileBase.class:?]
        at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52) ~[je.class:?]
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187278_c(PlayerChunkMapEntry.java:175) ~[ot.class:?]
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187276_a(PlayerChunkMapEntry.java:74) ~[ot.class:?]
        at net.minecraft.server.management.PlayerChunkMap.func_72683_a(SourceFile:227) ~[ou.class:?]
        at net.minecraft.server.management.PlayerList.func_72375_a(PlayerList.java:289) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:377) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:165) ~[pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
```

This only started happening after building a 5x5x5 crafting multiblock inside a compact machine. After building the machine, I disconnected my crafters, and attempted to open them to remove the patterns. The server crashed, and after rebooting and reconnecting, I can no longer connect to the system. The server doesn't crash anymore, but that error is dumped into the server log and I am kicked upon connection. 

Server crash log attached. Running Direwolf20 1.12 modpack v1.3.0 on macOS High Sierra for both server and client. 

[crash-2017-12-15_18.08.59-server.txt](https://github.com/TechReborn/RebornStorage/files/1564359/crash-2017-12-15_18.08.59-server.txt)

**Comment by modmuss50** [comment]
I have no idea what could be causing this, as the crash is happening in Refined storage I cannot make a work around for it. If anyone has any suggestions please let me know. Thanks.

**Comment by romulous75** [comment]
This is fixed in DW20 1.12.2 (v1.4.0 of the pack). I have no problems loading the world and using the multi block.

**Comment by gigabit101** [comment]
So I moved my DW20 server over to 1.4.0 and mine still works fine.
This seems to be a hit or miss issue

**Comment by Chasewhip8** [comment]
We had corrupted chunks on our server and had to role back to our last backup. Used a 5x5x5 and got a endless crash loop on DW20 1.3.0 and got @jmarler 's crash on server join when updated to DW20 v4.0

**Comment by raoulvdberge** [comment]
@modmuss50 

This is the cause:
- you place a reborn storage block
- you break the reborn storage block
- you place an RS block in place of the reborn storage block
   - RS expects an RS node, but got a reborn storage node
   - conclusion: reborn storage didn't correctly remove the reborn storage node

Exact cause:
Reborn storage network node isn't removed correctly upon calling breakBlock.

This should be called:
https://github.com/TechReborn/RebornStorage/blob/1.12/src/main/java/me/modmuss50/rebornstorage/blocks/BlockMultiCrafter.java#L152

But for some reason it's not called.
Looking up, I see a `return`, making the `removeNode` call never being called:
https://github.com/TechReborn/RebornStorage/blob/1.12/src/main/java/me/modmuss50/rebornstorage/blocks/BlockMultiCrafter.java#L140
