### ISSUE TITLE
Crash on joining server

### ISSUE THREAD

**Issue by InsaneJ** [TechReborn/RebornStorage#8]
People are reporting crashes when they join our server. Not sure if it's caused by Reborn Storage. Posting just in case.

Crash report: http://paste2.org/5JHGx1aH

`Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.<init>(CraftingPattern.java:53)
	at com.raoulvdberge.refinedstorage.item.ItemPattern.create(ItemPattern.java:210)
	at RebornStorage.multiblocks.MultiBlockCrafter.rebuildPatterns(MultiBlockCrafter.java:207)
	at RebornStorage.tiles.TileMultiCrafter.func_73660_a(TileMultiCrafter.java:121)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)`

**Comment by Heptagon-ru** [comment]
I have the same issue on the server.  6Gb memory for Java, 2 chunk distance, fast graphics, better foliage off.
Report: http://paste2.org/b4KgUe0L

**Comment by modmuss50** [comment]
Anychance you could send me a world that I could use to test this issue.

**Comment by InsaneJ** [comment]
Sure, how do I contact you? We're using our own mod pack which may not be distributed publicly.

**Comment by modmuss50** [comment]
We have a discord server: https://discord.gg/0tCDWb77cvetwm0e If that isnt sutible let me know. If its too much of a pain to send me the world it doesnt matter.

**Comment by InsaneJ** [comment]
Sorry, I don't use Discord.
What extra information do you hope to get from loading the world that's not in the crash-report?

**Comment by modmuss50** [comment]
It doesnt matter, I should be able to sort it out anyway. I will see what I can do.

**Comment by gigabit101** [comment]
I can not reproduce this issue
